// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/watariRyo/go-echo-redis/server/conf"
	"github.com/watariRyo/go-echo-redis/server/domain"
	"github.com/watariRyo/go-echo-redis/server/handler"
	"github.com/watariRyo/go-echo-redis/server/repository"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(configApiServer *conf.ApiServer, db *gorm.DB) *Server {
	userRepository := repository.NewUserRepository()
	loginDomain := domain.NewLoginDomain(userRepository)
	loginHandler := handler.NewLoginHandler(loginDomain)
	signUpDomain := domain.NewSignUpDomain(userRepository)
	signUpHandler := handler.NewSignUpHandler(signUpDomain)
	testDomain := domain.NewTestDomain()
	testHandler := handler.NewTestHandler(testDomain)
	server := NewServer(configApiServer, userRepository, loginDomain, loginHandler, signUpDomain, signUpHandler, testDomain, testHandler)
	return server
}
